// fileTransport.js - Asynchronous file transport with daily rotation and gzip compression

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');
const { format } = require('date-fns');

// Configuration
const LOG_DIR = path.resolve(__dirname, '..', 'logs');
const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10 MB

// Retain logs forever by default, unless configured otherwise
let maxLogFiles = false;
let maxExpireDays = false;

function init(config) {
  if (config) {
    if (config.maxLogFiles !== undefined) maxLogFiles = config.maxLogFiles;
    if (config.maxExpireDays !== undefined) maxExpireDays = config.maxExpireDays;
  }
}

// Ensure log directory exists
if (!fs.existsSync(LOG_DIR)) {
  fs.mkdirSync(LOG_DIR, { recursive: true });
}

let currentStream = null;
let currentLogPath = '';
let currentSize = 0;

function getLogFileName() {
  const datePart = format(new Date(), 'yyyy-MM-dd');
  return `log-${datePart}.log`;
}

function openNewLogStream() {
  const fileName = getLogFileName();
  currentLogPath = path.join(LOG_DIR, fileName);
  currentStream = fs.createWriteStream(currentLogPath, { flags: 'a' });
  currentSize = fs.existsSync(currentLogPath) ? fs.statSync(currentLogPath).size : 0;
  
  // Clean up old logs whenever we open a new stream (e.g. daily)
  cleanupOldLogs();
}

function cleanupOldLogs() {
  if (maxLogFiles === false && maxExpireDays === false) return;

  fs.readdir(LOG_DIR, (err, files) => {
    if (err) {
      console.error('Error reading log directory for cleanup:', err);
      return;
    }

    // Only process files generated by this logger
    const targetFiles = files.filter(f => f.startsWith('log-'));
    if (targetFiles.length === 0) return;

    let processedCount = 0;
    const logFiles = [];

    targetFiles.forEach(file => {
      const filePath = path.join(LOG_DIR, file);
      fs.stat(filePath, (err, stats) => {
        processedCount++;
        if (!err) {
          logFiles.push({ name: file, path: filePath, mtimeMs: stats.mtimeMs });
        }
        
        if (processedCount === targetFiles.length) {
          performCleanup(logFiles);
        }
      });
    });
  });
}

function performCleanup(logFiles) {
  const now = Date.now();
  // Sort descending by modification time (newest first)
  logFiles.sort((a, b) => b.mtimeMs - a.mtimeMs);

  // 1. Enforce maxLogFiles (keep only the newest X files)
  if (maxLogFiles !== false && maxLogFiles > 0) {
    if (logFiles.length > maxLogFiles) {
      const filesToDelete = logFiles.splice(maxLogFiles); // keep only maxLogFiles in array
      filesToDelete.forEach(f => {
        fs.unlink(f.path, err => {
          if (err && err.code !== 'ENOENT') console.error(`Failed to delete old log file: ${f.path}`, err);
        });
      });
    }
  }

  // 2. Enforce maxExpireDays (delete anything older than X days from remaining)
  if (maxExpireDays !== false && maxExpireDays > 0) {
    const maxAgeMs = maxExpireDays * 24 * 60 * 60 * 1000;
    logFiles.forEach(f => {
      const ageMs = now - f.mtimeMs;
      if (ageMs > maxAgeMs) {
        fs.unlink(f.path, err => {
           if (err && err.code !== 'ENOENT') console.error(`Failed to delete expired log file: ${f.path}`, err);
        });
      }
    });
  }
}

function rotateIfNeeded() {
  if (!currentStream) {
    openNewLogStream();
    return;
  }
  // Rotate daily based on filename change
  const expectedName = getLogFileName();
  if (!currentLogPath.endsWith(expectedName)) {
    closeCurrentStream();
    openNewLogStream();
    return;
  }
  // Rotate by size
  if (currentSize >= MAX_FILE_SIZE) {
    closeCurrentStream();
    // Rename old file with timestamp
    const timestamp = format(new Date(), 'HHmmss');
    const rotatedName = `${currentLogPath}.${timestamp}`;
    fs.renameSync(currentLogPath, rotatedName);
    // Gzip the rotated file
    const gzip = zlib.createGzip();
    const source = fs.createReadStream(rotatedName);
    const destination = fs.createWriteStream(`${rotatedName}.gz`);
    source.pipe(gzip).pipe(destination);
    // Delete the uncompressed rotated file after compression finishes
    destination.on('finish', () => {
      fs.unlinkSync(rotatedName);
    });
    openNewLogStream();
  }
}

function closeCurrentStream() {
  if (currentStream) {
    currentStream.end();
    currentStream = null;
  }
}

function write(logEntry) {
  rotateIfNeeded();
  if (!currentStream) {
    openNewLogStream();
  }
  currentStream.write(logEntry);
  currentSize += Buffer.byteLength(logEntry);
}

module.exports = {
  init,
  write,
  close: closeCurrentStream,
};
